# Base de datos en memoria

spring.datasource.url=jdbc:h2:mem:test
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# Base de Datos Local
#spring.datasource.url=jdbc:mysql://localhost/buscaprecio
#spring.datasource.username=root
#spring.datasource.password=1312

spring.datasource.hikari.maximum-pool-size = 1
spring.jpa.hibernate.ddl-auto = create-drop
spring.jpa.open-in-view = false

jpa.properties.hibernate.format_sql = true
jpa.properties.show-sql = true
