spring.application.name=api

spring.datasource.url=${BPRECIO_DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASS}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



